name: SimpleReserve
main: com.evosysdev.bukkit.taylorjb.simplereserve.SimpleReserve
version: 0.4.4
website: http://dev.bukkit.org/server-mods/simplereserve/
author: taylorjb
permissions:
    simplereserve.*:
        description: All SimpleReserve permissions
        children:
            simplereserve.enter: true
            simplereserve.kick.prevent: true
    simplereserve.enter:
        description: Enter full and kick permissions
        children:
            simplereserve.enter.full: true
            simplereserve.enter.kick: true
    simplereserve.enter.full:
        description: User may join past server player cap
    simplereserve.enter.kick:
        description: User may join full server by kicking another player
    simplereserve.kick.prevent:
        description: User cannot be kicked to make room for a joining player